#
# Codec Schema
#

# Codec Name
name: Tokenized Message Types

# Unique Identifier
package: messages

# Codec Version
version: 1

# Register Supported Messages
messages:
  - "general/0002 - Public Message"
  - "general/0003 - Private Message"
  - "general/0004 - Reverted Tx"
  - "commercial/1001 - Offer"
  - "commercial/1002 - Signature Request"
  - "commercial/1003 - Settlement Request"
  - "commercial/1004 - Output Metadata"

# Register Resources
resources: []

# Register Field Types
fieldTypes:
  - "types/Outpoint"
  - "types/OutputTag"
  - "types/Document"
  - "types/TargetAddress"

# Define Field Aliases
fieldAliases:
  - name: Tag
    type: uint
    size: 8
    resource: Tags
    description: "Predefined tags for output metadata."

  - name: Timestamp
    type: uint
    size: 8
    description: "Represents a time, encoded as a 64 bit unsigned integer representing the number of nanoseconds since the Unix epoch."
    example: "Wed May 09 2018 00:00:00 GMT+1000 (AEST)"

  - name: Address
    type: varbin
    description: "A representation of a bitcoin address in raw format, with no check sum or encoding."

  - name: TxId
    type: bin
    size: 32
    description: "Represents a Bitcoin transaction ID, the double SHA256 hash of the serialized transaction."
    example: "9d1ef0b1201c1dec3c1eb1caf758a988205226173e988e7a04afb4ea9977f506"
