#
# Codec Schema
#

# Codec Name
name: Tokenized Message Types

# Unique Identifier
package: messages

# Codec Version
version: 1

# Register Supported Messages
messages:
  - "general/0002 - Public Message"
  - "general/0003 - Private Message"
  - "general/0004 - Reverted Tx"
  - "commercial/1001 - Offer"
  - "commercial/1002 - Signature Request"
  - "commercial/1003 - Settlement Request"
  - "commercial/1004 - Output Metadata"
  - "commercial/1005 - Distribution"
  - "relationships/2001 - Initiate Relationship"
  - "relationships/2002 - Pending Accept Relationship"
  - "relationships/2003 - Accept Relationship"
  - "relationships/2004 - Relationship Amendment"
  - "relationships/2005 - Initiate Thread"

# Register Resources
resources:
  - "../../resources/develop/Entities"
  - "../../resources/develop/Roles"
  - "../../resources/develop/Tags"

# Register Field Types
fieldTypes:
  - "types/Administrator"
  - "types/ChannelParty"
  - "types/Document"
  - "types/Entity"
  - "types/IdentityOracleProof"
  - "types/Manager"
  - "types/OracleSignature"
  - "types/Outpoint"
  - "types/OutputTag"
  - "types/PaymailProof"
  - "types/Period"
  - "types/TargetAddress"

# Define Field Aliases
fieldAliases:
  - name: Tag
    type: uint
    size: 1
    resource: Tags
    description: "Predefined tags for output metadata."

  - name: Timestamp
    type: uint
    size: 8
    description: "Represents a time, encoded as a 64 bit unsigned integer representing the number of nanoseconds since the Unix epoch."
    example: 1594668650000000000

  - name: Address
    type: varbin
    varSize: small
    description: "A representation of a bitcoin address in raw format, with no check sum or encoding."

  - name: TxId
    type: bin
    size: 32
    description: "Represents a Bitcoin transaction ID, the double SHA256 hash of the serialized transaction."
    example: "9d1ef0b1201c1dec3c1eb1caf758a988205226173e988e7a04afb4ea9977f506"

  - name: ProofOfIdentityType
    description: "The type/format of the sender's proof of identity. 0 - not included, 1 - PaymailProof, 2 - IdentityOracleProof"
    type: uint
    size: 1
    options:
      - 0
      - 1
      - 2

  - name: EntityType
    type: fixedchar
    size: 1
    resource: Entities
    description: "A type of entity. (i.e. Individual, Public Company)"

  - name: Role
    type: uint
    size: 1
    resource: Roles
    description: "A role within an entity. (i.e. CEO, CFO)"

  - name: InstrumentCode
    type: bin
    size: 20
    description: "Represents a unique identifier for an instrument/token."
    example: "0e6996402ea456156838652e3bd82c6c0986ef79"
