#
# Codec Schema
#

# Codec Name
name: Tokenized Instrument Types

# Unique Identifier
package: instruments

# Codec Version
version: 1

# Register Supported Messages
messages:
  - "identity/MBR - Membership"
  - "currency/CCY - Currency"
  - "security/SHC - Common Share"
  - "security/BFR - Bond Fixed Rate"
  - "utility/COU - Coupon"
  - "utility/LOY - Loyalty Points"
  - "utility/TIC - Admission Ticket"
  - "utility/CHP - Casino Chip"
  - "utility/ISL - Information Service License"
  - "utility/ART - Asset Referenced Token"

# Register Resources
resources:
  - "../../resources/develop/Currencies"
  - "../../resources/develop/ReferencedAssetType"

# Register Field Types
fieldTypes:
  - "types/AgeRestriction"
  - "types/CurrencyValue"
  - "types/Rate"
  - "types/ReferencedAsset"

# Define Field Aliases
fieldAliases:
  - name: CurrencyType
    type: fixedchar
    size: 3
    description: >
      International Organization for Standardization code for Currency. 3 character code.
    example: AUD
    resource: Currencies

  - name: ReferencedAssetType
    type: uint
    size: 8
    description: Type of asset referenced by an Asset Referenced Token.
    example: 1
    resource: ReferencedAssetType

  - name: Timestamp
    type: uint
    size: 8
    description: >
      Represents a time, encoded as a 64 bit unsigned integer representing the number of nanoseconds
      since the Unix epoch.
    example: 1594668650000000000

  - name: TimestampSeconds
    type: uint
    size: 8
    description: >
      Represents a time encoded as a 64 bit unsigned integer representing the number of seconds
      since the Unix epoch.
    example: 1594668654

  - name: Seconds
    type: uint
    size: 8
    description: >
      Represents a time delta encoded as a 64 bit unsigned integer representing the number of
      seconds since a previous timestamp.
    example: 1500
